### ISSUE TITLE
Setup.makeEnvironment throws an exception if setup is incomplete

### ISSUE THREAD

**Issue by fthomas** [larsrh/libisabelle#19]
This can be reproduced by creating an empty setup directory:

``` shell
$ rm -rf .local/share/libisabelle/setups/Isabelle2015/
$ mkdir -p .local/share/libisabelle/setups/Isabelle2015/
```

Now, running this program

``` scala
val version = Version("2015")
val setup = Setup.defaultSetup(version)
val env = setup.flatMap(_.makeEnvironment)
Await.result(env, Duration.Inf)
```

yields the following exception

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at edu.tum.cs.isabelle.Implementations$.makeEnvironment(Implementations.scala:40)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at scala.Option.map(Option.scala:146)
        at edu.tum.cs.isabelle.Implementations.makeEnvironment(Implementations.scala:110)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:171)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:169)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: Cannot run program "/home/frank/.local/share/libisabelle/setups/Isabelle2015/bin/isabelle": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at isabelle.Isabelle_System$.raw_execute(isabelle_system.scala:284)
        at isabelle.Isabelle_System$.init(isabelle_system.scala:122)
        at edu.tum.cs.isabelle.impl.Environment.<init>(Environment.scala:13)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at edu.tum.cs.isabelle.Implementations$.makeEnvironment(Implementations.scala:40)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at scala.Option.map(Option.scala:146)
        at edu.tum.cs.isabelle.Implementations.makeEnvironment(Implementations.scala:110)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:171)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:169)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at isabelle.Isabelle_System$.raw_execute(isabelle_system.scala:284)
        at isabelle.Isabelle_System$.init(isabelle_system.scala:122)
        at edu.tum.cs.isabelle.impl.Environment.<init>(Environment.scala:13)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at edu.tum.cs.isabelle.Implementations$.makeEnvironment(Implementations.scala:40)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at edu.tum.cs.isabelle.Implementations$$anonfun$makeEnvironment$2.apply(Implementations.scala:110)
        at scala.Option.map(Option.scala:146)
        at edu.tum.cs.isabelle.Implementations.makeEnvironment(Implementations.scala:110)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:171)
        at edu.tum.cs.isabelle.setup.Setup$$anonfun$makeEnvironment$1.apply(Setup.scala:169)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Removing the Isabelle2015 directory and running the above program again fixes the problem.

It seems that this happened to me because the first download of Isabelle2015 was incomplete (there was only an empty `ANNOUNCE` file). It would be nice if libisabelle would check if a setup is complete before running `bin/isabelle`.

**Comment by larsrh** [comment]
The problem is that an Isabelle installation is "detected" by looking for a directory with the correct name. Proper solution would be to have an "automatic" and a "manual" mode: In automatic mode, it would expect a `.finished` file in the directory which is only written when extraction succeeds (which in turn is detected when the checksum of the archive matches and extraction didn't throw any exceptions).
